brew 'node'
brew 'watchman'
brew 'yarn'
brew 'kubernetes-cli'
# brew 'meld'
brew 'docker-completion'
cask 'gpg-suite'
brew 'ack'
brew 'autojump'
brew 'ctags'
brew 'jq'
brew 'most'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
